### ISSUE TITLE
Some metircs cannot be displayed at exposition

### ISSUE THREAD

**Issue by kash203** [twitter/rezolus#224] opened 2021-06-15 06:22 UTC
**① Several metrics cannot be displayed (interrupts sampler)**
If /proc/interrupts does not contain the metrics implemented in Rezolus, the following metircs in /proc/interrupts cannot store.

https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/interrupt/mod.rs#L175
https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/interrupt/mod.rs#L256
https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/interrupt/mod.rs#L260
It is because variable `line` is not cleared when the keyword did not match the implemented keywords and appended next line to `line`.
I think that line.clear() is needed before continue.

**② Active(anon), Inactive(anon) in /proc/meminfo cannot be displayed (memory sampler)**
https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/memory/mod.rs#L118
Above implementation cannot match the word including parentheses.

I think it should be below:
`                Regex::new(r"(?P<stat>.+):\s+(?P<value>\d+)").expect("failed to compile regex");`
(change \w to .)

**③ The node1 metrics is also displayed in the environments that have only node0 (interrupts sampler)**
I think the cause is below implementation.
https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/interrupt/mod.rs#L231
```
if let Some(previous) =
    result.get_mut(&InterruptStatistic::Node1Network)
{
    *previous += node1;
} else {
    result.insert(InterruptStatistic::Node1Network, sum);
}
```
As above implementation, `sum` variable for total value is used in Node1 metircs.
So only the value acquired for the first time is recorded in node1 regardless of node.
I think it should use `node1` instead of `sum`.

**④ Cstate is not displayed correctly (cpu sampler)**
In the environment using Intel Skylake CPU, Cstate name in `/sys/devices/system/cpu/{}/cpuidle/{}/name` can be given the suffix "-SKX".
A example is below.
```
cat /sys/devices/system/cpu/cpu0/cpuidle/state?/name
POLL
C1-SKX
C1E-SKX
C6-SKX
```
So under the environment, C1,C1E,C6 is not match the implementation.
https://github.com/twitter/rezolus/blob/41d4b1d196805cbd9a345af1b87c013c5fea1e99/src/samplers/cpu/stat.rs#L198

So I think it should be below:
```
        if s == "POLL" || s == "C0" {
            Ok(CState::C0)
        } else if s.starts_with("C1E") {
            Ok(CState::C1E)
        } else if s.starts_with("C1") {
            Ok(CState::C1)
        [..]
```

**Comment by kash203** [comment] 2021-06-15 06:57
And following metrics cannot also be displayed at exposition but I cannot find the implementation...
memory/hugetlb (memory sampler)
interrupt/serial (interrupts sampler)

**Comment by brayniac** [comment] 2021-06-18 18:02
Thanks for opening this. In the future, this would have been a little easier if we had separate issues for each issue instead of one larger issue that combines a bunch of different issues.

4 for the cstate names, what kernel are you seeing those cstate names on? I can't find any reference to C1E-SKX in the kernel sources. Maybe I'm missing something, but looks like these names come from: https://github.com/torvalds/linux/blob/f0728bfeb21a24bbb7d5ad1828b67a359550fa17/drivers/idle/intel_idle.c

1 and 3 confirmed as valid issues and addressed by #225 and #226 respectively.

2 confirmed as valid and addressed by #227.

5 is being fixed in #228 by removing that metric.

6 perhaps your kernel doesn't have the same configuration. https://github.com/torvalds/linux/blob/70585216fe7730d9fb5453d3e2804e149d0fe201/mm/hugetlb.c#L3712

Will leave this open to track 4. Thanks again

**Comment by kash203** [comment] 2021-06-21 01:10
Thank you for responding to it promptly!
I will raise them individually in future if there are some issues.

4 for the cstate names, it is written below.
https://github.com/torvalds/linux/commit/f9e71657c2c0a8f1c50884ab45794be2854e158e#diff-c7312d175ac317e1b4e34b7e9de8fb5a966d3194d4ae876828422b9fe619c7fe

This suffix is deleted in subsequent update below.
https://github.com/torvalds/linux/commit/de09cdd09fa12c3f837902680c3011d96e811821#diff-c7312d175ac317e1b4e34b7e9de8fb5a966d3194d4ae876828422b9fe619c7fe

But my environments kernel version is 3.10.0-862 , RHEL7.5 , it may be a little old.

6 
I overlooked this file, thank you for teaching!
(Hugetlb doesn't seem to be in the kernel version of my environment.)

**Comment by brayniac** [comment] 2021-06-29 21:19
#229 closes out the last of the issues raised here. Thanks again for the report. Closing

**Closed by brayniac** 2021-06-29 21:19 UTC
